name = "opvolging-it"
main = "src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "opvolging-it-db"
database_id = "69cc73c7-bef8-40d3-aeae-3b4954f033be"

[assets]
directory = "./public"
